### ISSUE TITLE
Not throwing any error or callback function not gets called

### ISSUE THREAD

**Issue by tamkin04iut** [apiaryio/fury-adapter-apib-parser#21]
Hi,

I ran the following code (adapter + fury) but didn't work.
```javascript
const apiParserAdaptor = require('fury-adapter-apib-parser');
fury.use(apiParserAdaptor);

// get "test.md" blueprint API doc from here "https://ufile.io/zklyt"
const path = __dirname + '/../docs/test.md';
fs.readFile(path, 'utf8', (err, data) => {
	fury.parse({source: data.toString()}, function(err, result) {
		console.log(err);
                console.log(result);
	});
})
```

But using `protagonist` it worked, I got the parsed object.

```javascript
// get "test.md" blueprint API doc from here "https://ufile.io/zklyt"
const path = __dirname + '/../docs/test.md';
fs.readFile(path, 'utf8', (err, data) => {
	protagonist.parse(data.toString(), function(error, result) {
		if (error) {
			return;
		}
	        console.log('here', JSON.stringify(result));
	});
});
```
**N.B.** "I have all json schema file definations realtive to `test.md` file"

Any Idea what could be wrong here?

**Comment by pksunkara** [comment]
What was the `err` and `result` logging in the first code?

**Comment by tamkin04iut** [comment]
Could you please have a look in this sandbox repo, https://github.com/tamkin04iut/fury-parse

* If you call `new Parser().parseWithProtagonist();` in `server.js` then it works and I can get parsed AST.
* If you call `new Parser().getAPIElement();` , you will notice that `callback` function `\fury-parse/src/parser/fury/blueprint-api-adapter/index.js:44` never gets called!.

**My Goal:**

* I would like to load all `docs/data-structure/index.md`
* Then I would like to load `docs/certificate/product-certificate.md` OR `docs/certificate/index.md` (For loading all dependent `.md` files)
* Finally, I want parsed APIElement, where I can query for JSON response (JSON structure) for each APIs.

**Comment by kylef** [comment]
The reason for this is that you have two conflicting versions of Protagonist installed at run-time. You have Protagonist 2.0.0-pre.0 along with Protagonist 1.6.8 installed (as a transitive dependency of fury-adapter-apib-parser).

You cannot have multiple versions of Protagonist as it is a Node Add-on and is a dynamically-linked module.

Applying the following patch, then run `rm -fr node_modules` and then `npm install` to remove the duplicate will allow this to work.

```diff
diff --git a/package.json b/package.json
index 72c2c68..506c230 100644
--- a/package.json
+++ b/package.json
@@ -22,6 +22,6 @@
     "fury-adapter-apiary-blueprint-parser": "^3.0.0-beta.3",
     "fury-adapter-apib-parser": "^0.10.0",
     "nodemon": "^1.12.4",
-    "protagonist": "^2.0.0-pre.0"
+    "protagonist": "1.6.8"
   }
 }
```

**Comment by tamkin04iut** [comment]
Thanks - @kylef !!, it worked .. Just wondering why 'fury-adapter-apib-parse' didn't use latest protagonist?

**Comment by kylef** [comment]
@tamkin04iut `2.0.0-pre.0` is a pre-release and isn't ready for full rollout across all of our tools. We are working on stabilising this version and then it will be updated for the final Protagonist 2.0.0.
