### ISSUE TITLE
The adapter should let me pass parsing options from outside

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/fury-adapter-apib-parser#8]
The current implementation is computing the `options` object from some of the properties passed to the `parse` function.

It would be definitely better if I could be able to pass the entire object from outside.

**Comment by pksunkara** [comment]
I think this needs to be changed in fury.js

**Comment by XVincentX** [comment]
Probably so. It would really help me unlock couple of situations.
It would be great if you can work on it!

**Comment by pksunkara** [comment]
@kylef Have you looked into this idea while adding requireBlueprintName option?

**Comment by kylef** [comment]
This has been supported already: https://github.com/apiaryio/fury.js/pull/65/files / https://github.com/apiaryio/fury-adapter-apib-parser/pull/9

``` js
var options = {
  source: req.body,
  mediaType: mediaType,
  adapterOptions: {
    requireBlueprintName: requireBlueprintName,
  },
};

fury.parse(options, function(err, parseResult) {
});
```
